import { createContext, useContext, useState } from 'react'

export type Language = 'es' | 'en'

interface LanguageContextValue {
  lang: Language
  setLang: (l: Language) => void
  t: (key: string) => string
}

const STORAGE_KEY = 'hb-lang'

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Sidebar
    'sidebar.menu':    'Menú',
    'sidebar.logout':  'Cerrar sesión',

    // Nav labels
    'nav.dashboard':    'Dashboard',
    'nav.applications': 'Aplicaciones',
    'nav.calendar':     'Calendario',
    'nav.documents':    'Documentos',
    'nav.settings':     'Configuración',

    // Calendar
    'calendar.title':        'Calendario',
    'calendar.subtitle':     'Tus postulaciones y eventos en el tiempo',
    'calendar.monthView':    'Mes',
    'calendar.listView':     'Lista',
    'calendar.today':        'Hoy',
    'calendar.noEvents':     'Sin eventos este período',
    'calendar.status':       'Estado',
    'calendar.date':         'Fecha',
    'calendar.type':         'Tipo',
    'calendar.typeApp':      'Postulación',
    'calendar.typeActivity': 'Actividad',
    'calendar.viewOffer':    'Ver oferta',
    'calendar.newEvent':     '+ Nuevo evento',
    'calendar.upcoming':     'Próximos eventos',
    'calendar.upcomingFrom': 'A partir de hoy,',
    'calendar.types':        'Tipos de evento',
    'calendar.typesDesc':    'Colores en el calendario',
    'calendar.save':         'Guardar',
    'calendar.formTitle':    'Título',
    'calendar.formCompany':  'Empresa',
    'calendar.formDate':     'Fecha',
    'calendar.formTime':     'Hora',

    // Dashboard
    'dashboard.title':    'Executive Intelligence',
    'dashboard.subtitle': 'Resumen de tu actividad.',
    'dashboard.export':   'Exportar Reporte',

    // StatsCards
    'stats.totalApps':       'Total Postulaciones',
    'stats.registered':      'registradas',
    'stats.noneYet':         'Ninguna aún',
    'stats.activeApps':      'Postulaciones Activas',
    'stats.rejected':        'rechazadas',
    'stats.noRejections':    'Sin rechazos',
    'stats.interviewRate':   'Tasa de Entrevistas',
    'stats.ofTotal':         'Del total de postulaciones',
    'stats.noInterviews':    'Sin entrevistas aún',
    'stats.cvsUploaded':     'CVs Subidos',
    'stats.available':       'disponible',
    'stats.availablePlural': 'disponibles',
    'stats.noneUploadedYet': 'Ninguno aún',
    'stats.coverLetters':    'Cartas de Presentación',
    'stats.noneClYet':       'Ninguna aún',
    'stats.activeOffers':    'Ofertas Activas',
    'stats.pendingReview':   'Pendiente de revisión',
    'stats.noOffers':        'Sin ofertas aún',

    // ConversionFunnel
    'funnel.title':     'Embudo de Conversión',
    'funnel.subtitle':  'Progresión de candidaturas por etapa',
    'funnel.last30':    'Últimos 30 días',
    'funnel.conv':      'conv.',

    // Timeline
    'timeline.title':   'Postulaciones en el Tiempo',
    'timeline.subtitle':'Aplicaciones enviadas por mes',
    'timeline.peak':    'Pico',
    'timeline.empty':   'Sin datos suficientes',
    'timeline.apps':    'postulaciones',

    // Sources
    'sources.title':    'Origen de Postulaciones',
    'sources.subtitle': 'Top plataformas utilizadas',

    // GhostingAnalytics
    'ghosting.title':   'Análisis de Respuestas',
    'ghosting.subtitle':'Tiempos de respuesta — últimos 30 días',
    'ghosting.fast':    'Respondió rápido',
    'ghosting.fastSub': '< 1 semana',
    'ghosting.late':    'Respuesta tardía',
    'ghosting.lateSub': '1–3 semanas',
    'ghosting.none':    'Sin respuesta',
    'ghosting.noneSub': '> 3 semanas',

    // RecentActivity
    'activity.title':       'Actividad Reciente',
    'activity.subtitle':    'Últimos movimientos en tus candidaturas',
    'activity.interview':   'Entrevista',
    'activity.applied':     'Postulación enviada',
    'activity.followup':    'Seguimiento enviado',
    'activity.scheduled':   'Entrevista agendada',
    'activity.rejected':    'Candidatura rechazada',
    'activity.offer':       'Oferta recibida',
    'activity.screening':   'En screening',
    'activity.yesterday':   'Ayer',
    'activity.today':       'Hoy',
    'activity.daysAgo1':    'Hace',
    'activity.daysAgo2':    'días',
    'activity.empty':       'Sin actividad reciente',

    // Applications page
    'apps.title':        'Mis Postulaciones',
    'apps.subtitle':     'Gestiona y analiza el estado de tus candidaturas activas.',
    'apps.list':         'Lista',
    'apps.board':        'Tablero',
    'apps.new':          'Nueva Postulación',
    'apps.salary':       'Salario',
    'apps.empty':        'No tienes postulaciones todavía',

    // Filters
    'filters.searchPlaceholder': 'Buscar por empresa o puesto…',
    'filters.status':            'Estado',
    'filters.relevance':         'Relevancia',
    'filters.anyStars':          'Cualquier relevancia',
    'filters.star':              'estrella',
    'filters.stars':             'estrellas',
    'filters.clear':             'Limpiar filtros',
    'filters.noResults':         'No se encontraron postulaciones con esos filtros',

    // ListView
    'list.company':     'Empresa & Rol',
    'list.source':      'Origen',
    'list.created':     'Creación',
    'list.updated':     'Actualización',
    'list.status':      'Estado',
    'list.relevance':   'Relevancia',
    'list.showing':     'Mostrando',
    'list.of':          'de',
    'list.applications':'postulaciones',

    // NewApplicationModal
    'new.title':           'Nueva Postulación',
    'new.subtitle':        'Registra una nueva candidatura en tu tablero.',
    'new.role':            'Rol / Puesto',
    'new.rolePlaceholder': 'ej. Senior Frontend Developer',
    'new.company':         'Empresa',
    'new.companyPlaceholder': 'ej. Stripe',
    'new.modality':        'Modalidad',
    'new.remote':          'Remoto',
    'new.hybrid':          'Híbrido',
    'new.onsite':          'Presencial',
    'new.status':          'Estado',
    'new.source':          'Origen de la oferta',
    'new.link':            'Link de la oferta (opcional)',
    'new.salary':          'Salario (opcional)',
    'new.salaryPlaceholder':'ej. $120,000 o $80k - $100k',
    'new.relevance':       'Relevancia',
    'new.cvLabel':         'CV a usar',
    'new.cvPlaceholder':   'Selecciona un CV…',
    'new.clLabel':         'Carta de Presentación',
    'new.clPlaceholder':   'Selecciona una carta…',
    'new.notes':           'Notas (opcional)',
    'new.notesPlaceholder':'Agrega contexto, contactos, próximos pasos...',
    'new.cancel':          'Cancelar',
    'new.save':            'Guardar Postulación',
    'new.sourceRequired':  'obligatorio',
    'apps.addSuccess':     'Postulación añadida correctamente',
    'new.searchCV':        'Buscar CV...',
    'new.searchCL':        'Buscar carta...',
    'new.noResults':       'Sin resultados para',
    'new.principal':       'Principal',

    // ApplicationModal
    'modal.info':              'Información',
    'modal.activity':          'Actividad',
    'modal.dateApplied':       'Fecha de aplicación',
    'modal.salary':            'Salario',
    'modal.salaryPlaceholder': 'ej. $80k – $120k',
    'modal.contact':           'Contacto / Recruiter',
    'modal.contactPlaceholder':'Nombre y cargo',
    'modal.offerLink':         'Link de la oferta',
    'modal.offerSource':       'Origen de la oferta',
    'modal.notes':             'Notas',
    'modal.notesPlaceholder':  'Contexto, requisitos importantes, próximos pasos...',
    'modal.addEvent':          'Añadir evento',
    'modal.newEvent':          'Nuevo evento',
    'modal.eventPlaceholder':  'ej. Entrevista técnica, Me llamaron…',
    'modal.notePlaceholder':   'Nota opcional…',
    'modal.cancel':            'Cancelar',
    'modal.saveEvent':         'Guardar evento',
    'modal.noActivity':        'Sin actividad registrada',
    'modal.noActivitySub':     'Añade entrevistas, llamadas y actualizaciones del proceso',
    'modal.done':              'Listo',
    'modal.saveChanges':       'Guardar Cambios',

    // Event presets
    'event.sent':           'Postulación enviada',
    'event.firstContact':   'Primer contacto del recruiter',
    'event.phoneScreen':    'Screening telefónico',
    'event.techInterview':  'Entrevista técnica',
    'event.hrInterview':    'Entrevista con RRHH',
    'event.teamInterview':  'Entrevista con el equipo',
    'event.testSent':       'Prueba técnica enviada',
    'event.testDelivered':  'Prueba técnica entregada',
    'event.offerReceived':  'Oferta recibida',
    'event.salaryNeg':      'Negociación de salario',
    'event.offerAccepted':  'Oferta aceptada',
    'event.rejected':       'Rechazada',
    'event.noResponse':     'Sin respuesta',

    // Status labels
    'status.applied':     'Aplicada',
    'status.inProcess':   'En Proceso',
    'status.screening':   'Screening',
    'status.interview':   'Entrevista',
    'status.offer':       'Oferta',
    'status.ghosted':     'Ghosteado',
    'status.rejected':    'Rechazada',

    // CV Page
    'cv.title':         'Documentos',
    'cv.subtitle':      'Gestiona tus CVs y cartas de presentación para reutilizarlos en tus postulaciones.',
    'cv.addCV':         'Añadir CV',
    'cv.newCL':         'Nueva Carta',
    'cv.tabCV':         'CVs',
    'cv.tabCL':         'Cartas de Presentación',
    'cv.colStar':       '★',
    'cv.colId':         'ID',
    'cv.colName':       'Nombre',
    'cv.colDate':       'Fecha',
    'cv.colSize':       'Tamaño',
    'cv.colNamePreview':'Nombre & Vista previa',
    'cv.emptyCVs':      'No hay CVs aún',
    'cv.addFirst':      '+ Añadir el primero',
    'cv.emptyCLs':      'No hay cartas aún',
    'cv.createFirst':   '+ Crear la primera',
    'cv.primary':       'Principal',
    'cv.pageOf':        'de',
    'cv.page':          'Página',
    'cv.deleteCVTitle': '¿Eliminar este CV?',
    'cv.deleteCVDesc':  'será eliminado. Tendrás 5 segundos para deshacer la acción.',
    'cv.deleteCLTitle': '¿Eliminar esta carta?',
    'cv.deleteCLDesc':  'será eliminada. Tendrás 5 segundos para deshacer la acción.',
    'cv.confirmDelete': 'Sí, eliminar',
    'cv.toastCV':         'CV eliminado',
    'cv.uploadSuccess':   'CV subido correctamente',
    'cv.clSaveSuccess':   'Carta guardada correctamente',
    'cv.toastCL':       'Carta eliminada',

    // CVDetailPage
    'detail.notFound':     'CV no encontrado',
    'detail.backToCVs':    'Volver a Mis CVs',
    'detail.back':         'Volver',
    'detail.markPrimary':  'Marcar principal',
    'detail.download':     'Descargar',
    'detail.delete':       'Eliminar',
    'detail.noPreview':    'Vista previa no disponible.',
    'detail.uploadPDF':    'Sube un PDF real para verlo aquí.',

    // UploadModal
    'upload.title':         'Añadir CV',
    'upload.subtitle':      'Sube un archivo PDF para guardarlo en tu biblioteca.',
    'upload.dropzone':      'Arrastra tu PDF aquí',
    'upload.or':            'o',
    'upload.click':         'haz clic para seleccionar',
    'upload.hint':          'Solo archivos PDF · Máx. 10 MB',
    'upload.markPrimary':   'Marcar como CV principal',
    'upload.markPrimarySub':'Se usará por defecto al añadir una postulación',
    'upload.cancel':        'Cancelar',
    'upload.save':          'Guardar CV',
    'upload.uploading':     'Subiendo...',

    // CoverLetterModal
    'cl.editTitle':      'Editar Carta',
    'cl.editSubtitle':   'Modifica el contenido de tu carta.',
    'cl.newTitle':       'Nueva Carta de Presentación',
    'cl.newSubtitle':    'Escribe y guarda tu carta para reutilizarla en postulaciones.',
    'cl.nameLabel':      'Nombre de la carta',
    'cl.namePlaceholder':'ej. Carta para startups de IA',
    'cl.contentLabel':   'Contenido',
    'cl.chars':          'caracteres',
    'cl.placeholder':    'Estimado equipo,\n\nMe dirijo a ustedes con gran entusiasmo para postularme al puesto de…',
    'cl.markPrimary':    'Marcar como carta principal',
    'cl.markPrimarySub': 'Se usará por defecto al añadir una postulación',
    'cl.cancel':              'Cancelar',
    'cl.errorNameRequired':   'El nombre es obligatorio',
    'cl.errorNameMax':        'El nombre no puede superar los 80 caracteres',
    'cl.errorContentRequired':'El contenido es obligatorio',
    'cl.errorContentMax':     'El contenido no puede superar los 1.500 caracteres',
    'cl.saveEdit':       'Guardar Cambios',
    'cl.saveNew':        'Guardar Carta',

    // Settings
    'settings.title':         'Configuración',
    'settings.subtitle':      'Administra tus preferencias personales, seguridad de la cuenta y exportación de datos.',
    'settings.profile':       'Perfil de Usuario',
    'settings.noName':        'Sin nombre',
    'settings.googlePhoto':   'Foto sincronizada con Google',
    'settings.fullName':      'Nombre Completo',
    'settings.email':         'Correo Electrónico',
    'settings.phone':         'Teléfono',
    'settings.phonePlaceholder': '+1 (555) 000-0000',
    'settings.phoneHint':     'Opcional',
    'settings.phoneError':    'Número inválido — solo dígitos (7–15), puede incluir +, espacios o guiones',
    'settings.saved':         'Guardado',
    'settings.saving':        'Guardando...',
    'settings.saveChanges':   'Guardar Cambios',
    'settings.exportTitle':   'Exportar Datos',
    'settings.exportDesc':    'Tus datos te pertenecen. Exporta todo tu historial, notas y métricas en formato CSV o PDF.',
    'settings.exportCSV':     'Exportar a CSV',
    'settings.exportPDF':     'Generar Reporte PDF',
    'export.loading':         'Generando...',
    'settings.importTitle':   'Importar Datos',
    'settings.importFeat1':   'Empresa, puesto y estado',
    'settings.importFeat2':   'Fecha de aplicación',
    'settings.importFeat3':   'Fuente y notas',
    'settings.importBtn':     'Importar desde Excel',
    'import.title':           'Importar desde Excel',
    'import.subtitle':        'Soporta el formato del Job Tracker (.xlsx)',
    'import.dragDrop':        'Arrastrá tu archivo .xlsx acá',
    'import.orClick':         'o hacé click para seleccionar',
    'import.noRows':          'No se encontraron filas válidas en el archivo.',
    'import.parseError':      'No se pudo leer el archivo. Asegurate de que sea un .xlsx válido.',
    'import.columnsTitle':    'Columnas reconocidas',
    'import.changeFile':      'Cambiar archivo',
    'import.readyCount':      'aplicaciones listas para importar',
    'import.success':         'aplicaciones importadas!',
    'import.successSub':      'Ya aparecen en tu tablero.',
    'import.goToApps':        'Ir a aplicaciones',
    'import.cancel':          'Cancelar',
    'import.importBtn':       'Importar',
    'import.importing':       'Importando...',
    'settings.security':      'Seguridad',
    'settings.googleLinked':  'Podés iniciar sesión con tu cuenta de Google',
    'settings.linked':        'Vinculado',
    'settings.password':      'Contraseña',
    'settings.passwordDesc':  'Podés iniciar sesión con email y contraseña',
    'settings.cancelPw':      'Cancelar',
    'settings.changePw':      'Cambiar contraseña',
    'settings.newPw':         'Nueva contraseña',
    'settings.confirmPw':     'Confirmar contraseña',
    'settings.updatePw':      'Actualizar contraseña',
    'settings.updatingPw':    'Guardando...',
    'settings.onlyGoogle':    'Tu cuenta usa Google para autenticarse. No necesitás una contraseña separada.',
    'settings.appearance':    'Apariencia',
    'settings.appearanceDesc':'Elige el tema de color de la interfaz. El cambio se aplica al instante.',
    'theme.default.desc':  'Púrpura oscuro — el look clásico de Trackbook.',
    'theme.midnight.desc': 'Azul profundo con acentos eléctricos.',
    'theme.emerald.desc':  'Pizarra oscura con acentos verdes.',
    'theme.rose.desc':     'Oscuro con acentos rosa vibrante.',
    'theme.light.desc':    'Blanco limpio con acentos púrpura.',
    'settings.dangerZone':    'Zona de Peligro',
    'settings.deleteAccount': 'Eliminar cuenta',
    'settings.deleteDesc':    'Borra permanentemente tu cuenta y todos tus datos. Esta acción no se puede deshacer.',
    'settings.rolLabel':      'Rol Profesional',
    'settings.rolPlaceholder':'Ej: Frontend Developer',
    'settings.pwErrorFields':  'Completa todos los campos',
    'settings.pwErrorMatch':   'Las contraseñas no coinciden',
    'settings.pwErrorLength':  'La contraseña debe tener al menos 8 caracteres',

    // DeleteModal
    'delete.title':     'Eliminar cuenta permanentemente',
    'delete.desc':      'Esta acción es irreversible. Se eliminarán todas tus postulaciones, CVs, cartas y datos de perfil para siempre.',
    'delete.type':      'Escribe',
    'delete.toConfirm': 'para confirmar',
    'delete.word':      'ELIMINAR',
    'delete.cancel':    'Cancelar',
    'delete.deleting':  'Eliminando...',
    'delete.confirm':   'Eliminar mi cuenta',

    // CVPrincipalCard
    'cvCard.title':      'CV Principal',
    'cvCard.desc':       'Este CV se usará por defecto al agregar una postulación.',
    'cvCard.empty':      'No tienes CVs guardados',
    'cvCard.onlyOne':    'Solo tienes un CV — se estableció como principal automáticamente.',
    'cvCard.select':     'Selecciona un CV principal…',

    // CoverLetterPrincipalCard
    'clCard.title':      'Carta de Presentación Principal',
    'clCard.desc':       'Esta carta se usará por defecto al agregar una postulación.',
    'clCard.empty':      'No tienes cartas guardadas',
    'clCard.onlyOne':    'Solo tienes una carta — se estableció como principal automáticamente.',
    'clCard.select':     'Selecciona una carta principal…',
    'clCard.preview':    'Vista previa',

    // Login
    'login.title':          'Iniciar sesión',
    'login.subtitle':       'Accedé a tu panel de gestión de ofertas.',
    'login.google':         'Continuar con Google',
    'login.connecting':     'Conectando...',
    'login.orEmail':        'O CON CORREO',
    'login.email':          'Email',
    'login.emailPlaceholder':'nombre@empresa.com',
    'login.sendLink':       'Enviar link de acceso',
    'login.sending':        'Enviando...',
    'login.hint':           'Te enviamos un link seguro al correo. Sin contraseña.',
    'login.checkEmail':     'Revisá tu correo',
    'login.sentTo':         'Enviamos un link de acceso a',
    'login.instructions':   'Hacé click en el botón del correo para entrar.\nEl link expira en 1 hora y es de un solo uso.',
    'login.useOther':       'Usar otro correo',

    // SessionExpired
    'expired.title':    'Sesión finalizada',
    'expired.desc':     'Estuviste inactivo por 30 minutos y tu sesión se cerró automáticamente para proteger tu cuenta.',
    'expired.cta':      'Volver al inicio de sesión',
    'expired.safe':     'Tu información está segura. Iniciá sesión nuevamente para continuar.',

    // Toast
    'toast.profileSaved': 'Cambios guardados correctamente',
    'toast.passwordSaved': 'Contraseña actualizada correctamente',
  },

  en: {
    // Sidebar
    'sidebar.menu':    'Menu',
    'sidebar.logout':  'Sign out',

    // Nav labels
    'nav.dashboard':    'Dashboard',
    'nav.applications': 'Applications',
    'nav.calendar':     'Calendar',
    'nav.documents':    'Documents',
    'nav.settings':     'Settings',

    // Calendar
    'calendar.title':        'Calendar',
    'calendar.subtitle':     'Your applications and events over time',
    'calendar.monthView':    'Month',
    'calendar.listView':     'List',
    'calendar.today':        'Today',
    'calendar.noEvents':     'No events this period',
    'calendar.status':       'Status',
    'calendar.date':         'Date',
    'calendar.type':         'Type',
    'calendar.typeApp':      'Application',
    'calendar.typeActivity': 'Activity',
    'calendar.viewOffer':    'View offer',
    'calendar.newEvent':     '+ New event',
    'calendar.upcoming':     'Upcoming events',
    'calendar.upcomingFrom': 'From today,',
    'calendar.types':        'Event types',
    'calendar.typesDesc':    'Colors in the calendar',
    'calendar.save':         'Save',
    'calendar.formTitle':    'Title',
    'calendar.formCompany':  'Company',
    'calendar.formDate':     'Date',
    'calendar.formTime':     'Time',

    // Dashboard
    'dashboard.title':    'Executive Intelligence',
    'dashboard.subtitle': 'Overview of your activity.',
    'dashboard.export':   'Export Report',

    // StatsCards
    'stats.totalApps':       'Total Applications',
    'stats.registered':      'registered',
    'stats.noneYet':         'None yet',
    'stats.activeApps':      'Active Applications',
    'stats.rejected':        'rejected',
    'stats.noRejections':    'No rejections',
    'stats.interviewRate':   'Interview Rate',
    'stats.ofTotal':         'Of total applications',
    'stats.noInterviews':    'No interviews yet',
    'stats.cvsUploaded':     'CVs Uploaded',
    'stats.available':       'available',
    'stats.availablePlural': 'available',
    'stats.noneUploadedYet': 'None yet',
    'stats.coverLetters':    'Cover Letters',
    'stats.noneClYet':       'None yet',
    'stats.activeOffers':    'Active Offers',
    'stats.pendingReview':   'Pending review',
    'stats.noOffers':        'No offers yet',

    // ConversionFunnel
    'funnel.title':     'Conversion Funnel',
    'funnel.subtitle':  'Application progression by stage',
    'funnel.last30':    'Last 30 days',
    'funnel.conv':      'conv.',

    // Timeline
    'timeline.title':   'Applications Over Time',
    'timeline.subtitle':'Applications submitted per month',
    'timeline.peak':    'Peak',
    'timeline.empty':   'Not enough data',
    'timeline.apps':    'applications',

    // Sources
    'sources.title':    'Application Sources',
    'sources.subtitle': 'Top platforms used',

    // GhostingAnalytics
    'ghosting.title':    'Response Analytics',
    'ghosting.subtitle': 'Response times — last 30 days',
    'ghosting.fast':     'Quick response',
    'ghosting.fastSub':  '< 1 week',
    'ghosting.late':     'Late response',
    'ghosting.lateSub':  '1–3 weeks',
    'ghosting.none':     'No response',
    'ghosting.noneSub':  '> 3 weeks',

    // RecentActivity
    'activity.title':       'Recent Activity',
    'activity.subtitle':    'Latest updates on your applications',
    'activity.interview':   'Interview',
    'activity.applied':     'Application sent',
    'activity.followup':    'Follow-up sent',
    'activity.scheduled':   'Interview scheduled',
    'activity.rejected':    'Application rejected',
    'activity.offer':       'Offer received',
    'activity.screening':   'In screening',
    'activity.yesterday':   'Yesterday',
    'activity.today':       'Today',
    'activity.daysAgo1':    '',
    'activity.daysAgo2':    'days ago',
    'activity.empty':       'No recent activity',

    // Applications page
    'apps.title':        'My Applications',
    'apps.subtitle':     'Manage and analyze the status of your active applications.',
    'apps.list':         'List',
    'apps.board':        'Board',
    'apps.new':          'New Application',
    'apps.salary':       'Salary',
    'apps.empty':        'You don\'t have any applications yet',

    // Filters
    'filters.searchPlaceholder': 'Search by company or role…',
    'filters.status':            'Status',
    'filters.relevance':         'Relevance',
    'filters.anyStars':          'Any relevance',
    'filters.star':              'star',
    'filters.stars':             'stars',
    'filters.clear':             'Clear filters',
    'filters.noResults':         'No applications match these filters',

    // ListView
    'list.company':     'Company & Role',
    'list.source':      'Source',
    'list.created':     'Created',
    'list.updated':     'Updated',
    'list.status':      'Status',
    'list.relevance':   'Relevance',
    'list.showing':     'Showing',
    'list.of':          'of',
    'list.applications':'applications',

    // NewApplicationModal
    'new.title':            'New Application',
    'new.subtitle':         'Register a new application on your board.',
    'new.role':             'Role / Position',
    'new.rolePlaceholder':  'e.g. Senior Frontend Developer',
    'new.company':          'Company',
    'new.companyPlaceholder':'e.g. Stripe',
    'new.modality':         'Work mode',
    'new.remote':           'Remote',
    'new.hybrid':           'Hybrid',
    'new.onsite':           'On-site',
    'new.status':           'Status',
    'new.source':           'Job source',
    'new.link':             'Job link (optional)',
    'new.salary':           'Salary (optional)',
    'new.salaryPlaceholder':'e.g. $120,000 or $80k - $100k',
    'new.relevance':        'Relevance',
    'new.cvLabel':          'CV to use',
    'new.cvPlaceholder':    'Select a CV…',
    'new.clLabel':          'Cover Letter',
    'new.clPlaceholder':    'Select a cover letter…',
    'new.notes':            'Notes (optional)',
    'new.notesPlaceholder': 'Add context, contacts, next steps...',
    'new.cancel':           'Cancel',
    'new.save':             'Save Application',
    'new.sourceRequired':   'required',
    'apps.addSuccess':      'Application added successfully',
    'new.searchCV':         'Search CV...',
    'new.searchCL':         'Search letter...',
    'new.noResults':        'No results for',
    'new.principal':        'Primary',

    // ApplicationModal
    'modal.info':              'Info',
    'modal.activity':          'Activity',
    'modal.dateApplied':       'Date applied',
    'modal.salary':            'Salary',
    'modal.salaryPlaceholder': 'e.g. $80k – $120k',
    'modal.contact':           'Contact / Recruiter',
    'modal.contactPlaceholder':'Name and position',
    'modal.offerLink':         'Job link',
    'modal.offerSource':       'Job source',
    'modal.notes':             'Notes',
    'modal.notesPlaceholder':  'Context, requirements, next steps...',
    'modal.addEvent':          'Add event',
    'modal.newEvent':          'New event',
    'modal.eventPlaceholder':  'e.g. Technical interview, They called me…',
    'modal.notePlaceholder':   'Optional note…',
    'modal.cancel':            'Cancel',
    'modal.saveEvent':         'Save event',
    'modal.noActivity':        'No activity recorded',
    'modal.noActivitySub':     'Add interviews, calls, and process updates',
    'modal.done':              'Done',
    'modal.saveChanges':       'Save Changes',

    // Event presets
    'event.sent':           'Application sent',
    'event.firstContact':   'First recruiter contact',
    'event.phoneScreen':    'Phone screen',
    'event.techInterview':  'Technical interview',
    'event.hrInterview':    'HR interview',
    'event.teamInterview':  'Team interview',
    'event.testSent':       'Technical test sent',
    'event.testDelivered':  'Technical test submitted',
    'event.offerReceived':  'Offer received',
    'event.salaryNeg':      'Salary negotiation',
    'event.offerAccepted':  'Offer accepted',
    'event.rejected':       'Rejected',
    'event.noResponse':     'No response',

    // Status labels
    'status.applied':     'Applied',
    'status.inProcess':   'In Process',
    'status.screening':   'Screening',
    'status.interview':   'Interview',
    'status.offer':       'Offer',
    'status.ghosted':     'Ghosted',
    'status.rejected':    'Rejected',

    // CV Page
    'cv.title':          'Documents',
    'cv.subtitle':       'Manage your CVs and cover letters to reuse in your applications.',
    'cv.addCV':          'Add CV',
    'cv.newCL':          'New Letter',
    'cv.tabCV':          'CVs',
    'cv.tabCL':          'Cover Letters',
    'cv.colStar':        '★',
    'cv.colId':          'ID',
    'cv.colName':        'Name',
    'cv.colDate':        'Date',
    'cv.colSize':        'Size',
    'cv.colNamePreview': 'Name & Preview',
    'cv.emptyCVs':       'No CVs yet',
    'cv.addFirst':       '+ Add the first one',
    'cv.emptyCLs':       'No cover letters yet',
    'cv.createFirst':    '+ Create the first one',
    'cv.primary':        'Primary',
    'cv.pageOf':         'of',
    'cv.page':           'Page',
    'cv.deleteCVTitle':  'Delete this CV?',
    'cv.deleteCVDesc':   'will be deleted. You have 5 seconds to undo.',
    'cv.deleteCLTitle':  'Delete this letter?',
    'cv.deleteCLDesc':   'will be deleted. You have 5 seconds to undo.',
    'cv.confirmDelete':  'Yes, delete',
    'cv.toastCV':         'CV deleted',
    'cv.uploadSuccess':   'CV uploaded successfully',
    'cv.clSaveSuccess':   'Cover letter saved successfully',
    'cv.toastCL':        'Letter deleted',

    // CVDetailPage
    'detail.notFound':    'CV not found',
    'detail.backToCVs':   'Back to My CVs',
    'detail.back':        'Back',
    'detail.markPrimary': 'Set as primary',
    'detail.download':    'Download',
    'detail.delete':      'Delete',
    'detail.noPreview':   'Preview not available.',
    'detail.uploadPDF':   'Upload a real PDF to view it here.',

    // UploadModal
    'upload.title':          'Add CV',
    'upload.subtitle':       'Upload a PDF file to save it to your library.',
    'upload.dropzone':       'Drag your PDF here',
    'upload.or':             'or',
    'upload.click':          'click to select',
    'upload.hint':           'PDF files only · Max. 10 MB',
    'upload.markPrimary':    'Set as primary CV',
    'upload.markPrimarySub': 'Will be used by default when adding an application',
    'upload.cancel':         'Cancel',
    'upload.save':           'Save CV',
    'upload.uploading':      'Uploading...',

    // CoverLetterModal
    'cl.editTitle':       'Edit Letter',
    'cl.editSubtitle':    'Modify the content of your letter.',
    'cl.newTitle':        'New Cover Letter',
    'cl.newSubtitle':     'Write and save your letter to reuse in applications.',
    'cl.nameLabel':       'Letter name',
    'cl.namePlaceholder': 'e.g. Letter for AI startups',
    'cl.contentLabel':    'Content',
    'cl.chars':           'characters',
    'cl.placeholder':     'Dear team,\n\nI am writing with great enthusiasm to apply for the position of…',
    'cl.markPrimary':     'Set as primary letter',
    'cl.markPrimarySub':  'Will be used by default when adding an application',
    'cl.cancel':               'Cancel',
    'cl.errorNameRequired':    'Name is required',
    'cl.errorNameMax':         'Name cannot exceed 80 characters',
    'cl.errorContentRequired': 'Content is required',
    'cl.errorContentMax':      'Content cannot exceed 1,500 characters',
    'cl.saveEdit':        'Save Changes',
    'cl.saveNew':         'Save Letter',

    // Settings
    'settings.title':          'Settings',
    'settings.subtitle':       'Manage your personal preferences, account security, and data export.',
    'settings.profile':        'User Profile',
    'settings.noName':         'No name',
    'settings.googlePhoto':    'Photo synced with Google',
    'settings.fullName':       'Full Name',
    'settings.email':          'Email Address',
    'settings.phone':          'Phone Number',
    'settings.phonePlaceholder': '+1 (555) 000-0000',
    'settings.phoneHint':      'Optional',
    'settings.phoneError':     'Invalid number — digits only (7–15), can include +, spaces or dashes',
    'settings.saved':          'Saved',
    'settings.saving':         'Saving...',
    'settings.saveChanges':    'Save Changes',
    'settings.exportTitle':    'Export Data',
    'settings.exportDesc':     'Your data belongs to you. Export your full history, notes, and metrics as CSV or PDF.',
    'settings.exportCSV':      'Export to CSV',
    'settings.exportPDF':      'Generate PDF Report',
    'export.loading':          'Generating...',
    'settings.importTitle':    'Import Data',
    'settings.importFeat1':    'Company, role and status',
    'settings.importFeat2':    'Application date',
    'settings.importFeat3':    'Source and notes',
    'settings.importBtn':      'Import from Excel',
    'import.title':            'Import from Excel',
    'import.subtitle':         'Supports the Job Tracker format (.xlsx)',
    'import.dragDrop':         'Drop your .xlsx file here',
    'import.orClick':          'or click to select',
    'import.noRows':           'No valid rows found in the file.',
    'import.parseError':       'Could not read the file. Make sure it is a valid .xlsx.',
    'import.columnsTitle':     'Recognized columns',
    'import.changeFile':       'Change file',
    'import.readyCount':       'applications ready to import',
    'import.success':          'applications imported!',
    'import.successSub':       'They now appear on your board.',
    'import.goToApps':         'Go to applications',
    'import.cancel':           'Cancel',
    'import.importBtn':        'Import',
    'import.importing':        'Importing...',
    'settings.security':       'Security',
    'settings.googleLinked':   'You can sign in with your Google account',
    'settings.linked':         'Linked',
    'settings.password':       'Password',
    'settings.passwordDesc':   'You can sign in with email and password',
    'settings.cancelPw':       'Cancel',
    'settings.changePw':       'Change password',
    'settings.newPw':          'New password',
    'settings.confirmPw':      'Confirm password',
    'settings.updatePw':       'Update password',
    'settings.updatingPw':     'Saving...',
    'settings.onlyGoogle':     'Your account uses Google to authenticate. You don\'t need a separate password.',
    'settings.appearance':     'Appearance',
    'settings.appearanceDesc': 'Choose the color theme for the interface. Changes apply instantly.',
    'theme.default.desc':  'Dark purple — the classic Trackbook look.',
    'theme.midnight.desc': 'Deep navy with electric blue accents.',
    'theme.emerald.desc':  'Dark slate with green accents.',
    'theme.rose.desc':     'Dark with vibrant rose-pink accents.',
    'theme.light.desc':    'Clean white with purple accents.',
    'settings.dangerZone':     'Danger Zone',
    'settings.deleteAccount':  'Delete account',
    'settings.deleteDesc':     'Permanently delete your account and all your data. This action cannot be undone.',
    'settings.rolLabel':       'Professional Role',
    'settings.rolPlaceholder': 'e.g. Frontend Developer',
    'settings.pwErrorFields':  'Fill in all fields',
    'settings.pwErrorMatch':   'Passwords do not match',
    'settings.pwErrorLength':  'Password must be at least 8 characters',

    // DeleteModal
    'delete.title':     'Permanently delete account',
    'delete.desc':      'This action is irreversible. All your applications, CVs, letters and profile data will be deleted forever.',
    'delete.type':      'Type',
    'delete.toConfirm': 'to confirm',
    'delete.word':      'DELETE',
    'delete.cancel':    'Cancel',
    'delete.deleting':  'Deleting...',
    'delete.confirm':   'Delete my account',

    // CVPrincipalCard
    'cvCard.title':      'Primary CV',
    'cvCard.desc':       'This CV will be used by default when adding an application.',
    'cvCard.empty':      'You have no saved CVs',
    'cvCard.onlyOne':    'You only have one CV — it was set as primary automatically.',
    'cvCard.select':     'Select a primary CV…',

    // CoverLetterPrincipalCard
    'clCard.title':      'Primary Cover Letter',
    'clCard.desc':       'This letter will be used by default when adding an application.',
    'clCard.empty':      'You have no saved cover letters',
    'clCard.onlyOne':    'You only have one letter — it was set as primary automatically.',
    'clCard.select':     'Select a primary cover letter…',
    'clCard.preview':    'Preview',

    // Login
    'login.title':           'Sign in',
    'login.subtitle':        'Access your job offer management panel.',
    'login.google':          'Continue with Google',
    'login.connecting':      'Connecting...',
    'login.orEmail':         'OR WITH EMAIL',
    'login.email':           'Email',
    'login.emailPlaceholder':'name@company.com',
    'login.sendLink':        'Send access link',
    'login.sending':         'Sending...',
    'login.hint':            'We\'ll send you a secure link. No password needed.',
    'login.checkEmail':      'Check your inbox',
    'login.sentTo':          'We sent an access link to',
    'login.instructions':    'Click the button in the email to sign in.\nThe link expires in 1 hour and is single-use.',
    'login.useOther':        'Use a different email',

    // SessionExpired
    'expired.title':    'Session ended',
    'expired.desc':     'You were inactive for 30 minutes and your session was automatically closed to protect your account.',
    'expired.cta':      'Back to sign in',
    'expired.safe':     'Your information is safe. Sign in again to continue.',

    // Toast
    'toast.profileSaved':  'Changes saved successfully',
    'toast.passwordSaved': 'Password updated successfully',
  },
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: 'es',
  setLang: () => {},
  t: (k) => k,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem(STORAGE_KEY)
    return saved === 'en' ? 'en' : 'es'
  })

  function setLang(l: Language) {
    localStorage.setItem(STORAGE_KEY, l)
    setLangState(l)
  }

  function t(key: string): string {
    return translations[lang][key] ?? key
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLang() {
  return useContext(LanguageContext)
}
